package com.demo.pojo;

import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   用户表 
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table users
 */
public class UsersEntity {
    /**
     * Database Column Remarks:
     *   主键id 用户id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.id")
    private String id;

    /**
     * Database Column Remarks:
     *   用户名 用户名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.username")
    private String username;

    /**
     * Database Column Remarks:
     *   密码 密码
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.password")
    private String password;

    /**
     * Database Column Remarks:
     *   昵称 昵称
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.nickname")
    private String nickname;

    /**
     * Database Column Remarks:
     *   真实姓名 真实姓名
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.realname")
    private String realname;

    /**
     * Database Column Remarks:
     *   头像 头像
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.face")
    private String face;

    /**
     * Database Column Remarks:
     *   手机号 手机号
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.mobile")
    private String mobile;

    /**
     * Database Column Remarks:
     *   邮箱地址 邮箱地址
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.email")
    private String email;

    /**
     * Database Column Remarks:
     *   性别 性别 1:男  0:女  2:保密
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.sex")
    private Integer sex;

    /**
     * Database Column Remarks:
     *   生日 生日
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.birthday")
    private Date birthday;

    /**
     * Database Column Remarks:
     *   创建时间 创建时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.created_time")
    private Date created_time;

    /**
     * Database Column Remarks:
     *   更新时间 更新时间
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.updated_time")
    private Date updated_time;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.id")
    public String getId() {
        return id;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.id")
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.username")
    public String getUsername() {
        return username;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.username")
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.password")
    public String getPassword() {
        return password;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.password")
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.nickname")
    public String getNickname() {
        return nickname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.nickname")
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.realname")
    public String getRealname() {
        return realname;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.realname")
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.face")
    public String getFace() {
        return face;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.face")
    public void setFace(String face) {
        this.face = face == null ? null : face.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.mobile")
    public String getMobile() {
        return mobile;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.mobile")
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.email")
    public String getEmail() {
        return email;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.email")
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.sex")
    public Integer getSex() {
        return sex;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.sex")
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.birthday")
    public Date getBirthday() {
        return birthday;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.birthday")
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.created_time")
    public Date getCreated_time() {
        return created_time;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.created_time")
    public void setCreated_time(Date created_time) {
        this.created_time = created_time;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.updated_time")
    public Date getUpdated_time() {
        return updated_time;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source field: users.updated_time")
    public void setUpdated_time(Date updated_time) {
        this.updated_time = updated_time;
    }
}